FROM node

WORKDIR /opt/app

COPY files/dev /opt/app
COPY files/node_modules /opt/app/node_modules
COPY docker-files/ssh-backup /root/.ssh

RUN apt update && \
    apt install -y ssh libltdl7 && \
    rm -rf /var/lib/apt/lists/* && \
    chmod -R o-rwx /root/.ssh && \
    chmod -R g-rwx /root/.ssh

CMD ["tail", "-f", "/dev/null"]
